### ISSUE TITLE
Please add Timeline Graph

### ISSUE THREAD

**Issue by francesco-loreti** [HHRy/prawn-graph#13]
Please add Timeline Graph as https://developers.google.com/chart/interactive/docs/gallery/timeline#a-simple-example

Or GANTT Chart as https://developers.google.com/chart/interactive/docs/gallery/ganttchart#overview

Thanks for your job!!

**Comment by HHRy** [comment]
Thanks for the request! I'll add it to the list of things to work on. Right now, I'm focusing on getting the gem ready for the proper 1.0 release, which means building test coverage, removing the legacy interface and finding and squashing bugs. 

If you want to have a go at adding support for it yourself though, I'd happy look over a pull request for it 😄 

~ Ry
