### ISSUE TITLE
Y axis not displaying correctly

### ISSUE THREAD

**Issue by fractaldirk** [HHRy/prawn-graph#16]
Hi, first of all thanks for making this gem!
I tried out your example:

```
require 'prawn-graph'

  series = []
  series << Prawn::Graph::Series.new([4,9,3,2,1,6,2,8,2,3,4,9,2],  title: "A label for a series", type: :bar)
  series << Prawn::Graph::Series.new([5,4,3,2,7,9,2,8,7,5,4,9,2],  title: "Another label", type: :line, mark_average: true, mark_minimum: true)
  series << Prawn::Graph::Series.new([1,2,3,4,5,9,6,4,5,6,3,2,11], title: "Yet another label", type: :bar)
  series << Prawn::Graph::Series.new([1,2,3,4,5,12,6,4,5,6,3,2,9].shuffle, title: "One final label", type: :line, mark_average: true, mark_maximum: true)

  xaxis_labels = ['0900', '1000', '1100', '1200', '1300', '1400', '1500', '1600', '1700', '1800', '1900', '2000', '2100']

  Prawn::Document.generate('test.pdf') do
    graph series, width: 500, height: 200, title: "A Title for the chart", at: [10,700], xaxis_labels: xaxis_labels
  end
```

When displaying it, it shows the y-axis with the values 12,9,12,9,12,9,11,12 instead of the correct values. Is this a dependency issue, any other way to set the Y axis manually?

Thanks,
Regards,
Dirk

**Comment by brianbancroft** [comment]
Hi there, 

I've also recently tried this and have run into similar problems. I took the hello-world example, and stripped it down to a single series: 
```
series = [Prawn::Graph::Series.new([5,4,3,2,7,9,2,8,7,5,4,9,2], type: :line, mark_average: false, mark_minimum: false)]
```
This is what I got: 
<img width="416" alt="screen shot 2016-10-30 at 8 08 52 pm" src="https://cloud.githubusercontent.com/assets/6225122/19841178/c8157f6c-9edc-11e6-8170-53138cff0e22.png">

If it helps, I'm running the following: 
Rails 5.0.0.1
ruby 2.3.1p112
... and the latest versions of the Prawn and Prawn-graph gems.

**Comment by randall-fulton** [comment]
This should be fixed with #17. Changes were tested with both of the examples provided here.

**Comment by brianbancroft** [comment]
Thank You!

**Comment by randall-fulton** [comment]
No problem @brianbancroft. This issue was causing me some problems in a project. Figured I might as well go ahead and fix it.

**Comment by HHRy** [comment]
Thank you so much for your fix for this. I've merged your request and will cut a new version of the gem today. Sorry for not being as active as I should be!  I really appreciate your help with this, @randall-fulton 😄

**Comment by randall-fulton** [comment]
No problem @HHRy. Glad I could help out.

**Comment by frankapimenta** [comment]
Is it possible to set the y axis for each serie of values?
