### ISSUE TITLE
Does it support horizontal bar chart?

### ISSUE THREAD

**Issue by gumatias** [HHRy/prawn-graph#19]
Hi, I was wondering if this library supports bar charts like the following:

![](https://www.ncsu.edu/labwrite/res/gh/horizbargraph.gif)

Thanks!

**Comment by randall-fulton** [comment]
Currently, prawn-graph does not support a horizontal bar chart.

**Comment by gumatias** [comment]
Gotcha! Are the any plans on doing so? I actually ended up building the chart from scratch, so I library help would be appreciated :)

On a side note, I've seen some people using Google Charts and placing the image on the file itself instead. I was curious if anyone had any thoughts on that as an alternative to a prawn graph library such as this one. thanks!

**Comment by HHRy** [comment]
Hey there, it's on the list of things to add in the future, but as Randall said, it doesn't support it at the moment.

You can totally embed a PNG or other image of a graph in the PDF document and there is a gem (I forget the name of it just now - sorry!) which does this.  The purpose of prawn-graph is to use only the native drawing tools of PDF to save the need to embed large blobs of data in your documents.
